apiVersion: v1
kind: Service
metadata:
  name: attributes
spec:
  selector:
    app: attributes
  type: NodePort
  ports:
    - name: http
      port: 8094
      nodePort: 30004

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: attributes
spec:
  selector:
    matchLabels:
      app: attributes
  replicas: 1
  template:
    metadata:
      labels:
        app: attributes
    spec:
      containers:
        - name: server
          image: 77anna77/attributes-service:latest
          ports:
            - name: http
              containerPort: 8094
