apiVersion: v1
kind: Service
metadata:
  name: devices
spec:
  selector:
    app: devices
  type: NodePort
  ports:
    - name: http
      port: 8092
      nodePort: 30002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devices
spec:
  selector:
    matchLabels:
      app: devices
  replicas: 1
  template:
    metadata:
      labels:
        app: devices
    spec:
      containers:
        - name: server
          image: 77anna77/device-service:latest
          ports:
            - name: http
              containerPort: 8092
