apiVersion: v1
kind: Service
metadata:
  name: telemetry
spec:
  selector:
    app: telemetry
  type: NodePort
  ports:
    - name: http
      port: 8093
      nodePort: 30003

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry
spec:
  selector:
    matchLabels:
      app: telemetry
  replicas: 1
  template:
    metadata:
      labels:
        app: telemetry
    spec:
      containers:
        - name: server
          image: 77anna77/telemetry-service:latest
          ports:
            - name: http
              containerPort: 8093
